template:
  namespace: broadcom
  name: test
  version: 1.0.0
  development: false
  description: test

pipelines:
  - name: new_hello_world_pipeline
    steps:
      - name: new_hello_world_pipeline_step_1
        type: Bash
        configuration:
          environmentVariables:
            test: true
        execution:
          onExecute:
            - echo {{ .Values.helloWorldMessage }}