resources:
  - name: git_resource
    type: GitRepo
    configuration:
      path: kunal-mazumdar/pipelines-local-test-repo
      gitProvider: kunal_gh
      branches:
        include: ^{{ gitBranch }}$

pipelines:
{{ range $i, $pipe := until 100 }}
  - name: loop_pipeline_{{ $i }}
    configuration:
      jfrogCliVersion: 2
    steps:
    {{ range $j, $step := until 100 }}
      - name: step_{{ $j }}
        type: Bash
        configuration:
          inputResources:
            - name: git_resource
        execution:
          onExecute:
            - echo "test1234513"
    {{ end }}
{{ end }}