valuesFilePath: ./values.yml

resources:
  - name: git_sonar
    type: CodeAnalysis
    configuration:
      tool: SonarCloud
      provider:
        integration: sonar_integration
        userNameKey: sonar_user_name
        tokenKey: sonar_token

pipelines:
  - name: code_analysis_pipe
    configuration:
      jfrogCliVersion: 2      
    steps:
      - name: my_first_step
        type: Bash
        configuration:
          inputResources:
            - name: git_sonar
        execution:
          onExecute:
            - echo "test"