resources:
  - name: pr_repo_a
    type: GitRepo
    configuration:
      gitProvider: kunal_gh
      path: kunal-mazumdar/pipelines-local-test-repo
      buildOn:
        branchCreate: false
        commit: true
        pullRequestCreate: false

  - name: myFileSpec1
    type: FileSpec
    configuration:
      sourceArtifactory: s_artifactory
      flat: true
      target: "/tmp"
      aql: "{\"items.find\":{\"$and\":[{\"repo\":\"jfrogpipelines\"},{\"name\":\"$FILE_NAME\"}]}}"

pipelines:
  - name: pr_pipe_x
    steps:
      - name: pr_step
        type: Bash
        configuration:
          environmentVariables:
            FILE_NAME: 'pipelines-template'
          inputResources:
            - name: pr_repo_a
            - name: myFileSpec1
        execution:
          onExecute:
            - echo ${res_pr_repo_a_isPullRequest}
            - echo $FILE_NAME
            - pushd /tmp
            - ls -al
