resources:
  - name: pr_repo_a
    type: GitRepo
    configuration:
      gitProvider: kunal_gh
      path: kunal-mazumdar/pipelines-local-test-repo
      buildOn:
        branchCreate: false
        commit: true
        pullRequestCreate: false

  - name: myAqlResource
    type: Aql
    configuration:
      sourceArtifactory: s_artifactory
      query: items.find({"repo":"example-repo-local"},{"name":"tools/pipelines-template"})

  - name: myFileSpec1
    type: FileSpec
    configuration:
      sourceArtifactory: s_artifactory
      flat: true
      target: "/tmp"
      aql: "{\"$and\":[{\"repo\":\"example-repo-local\"},{\"name\":\"tools/pipelines-template\"}]}"

pipelines:
  - name: pr_pipe_x
    steps:
      - name: pr_step
        type: Bash
        configuration:
          inputResources:
            - name: pr_repo_a
            - name: myAqlResource
            - name: myFileSpec1
        execution:
          onExecute:
            - echo ${res_pr_repo_a_isPullRequest}
