resources:
  - name: sample_nodejs_git
    type: GitRepo
    configuration:
      gitProvider: kunal_gh
      path: kunal-mazumdar/node-js-sample
      branches:
        include: master

  - name: yml_git
    type: GitRepo
    configuration:
      gitProvider: kunal_gh
      path: kunal-mazumdar/pipelines-local-test-repo
      branches:
        include: cache

pipelines:
  - name: local_cache_test
    configuration:
      nodePool: local_cache
      runtime:
        type: image
        image:
          custom:
            name: releases-docker.jfrog.io/jfrog/pipelines-u20node
            tag: 18.18.2
            options: "-v ~/node_modules:/root/node_modules:ro,rslave"

    steps:
      - name: test
        type: Bash
        configuration:
          inputResources:
            - name: sample_nodejs_git
            - name: yml_git
        execution:          
          onExecute:
            - ls -al /root
            - ls -las /root/node_modules
            - chmod -R 777 /root/node_modules
            - cd ${res_sample_nodejs_git_resourcePath}            
            - pwd
            - ls -las
            - npm config set cache /root/node_modules --global
            - npm i --verbose
            - ls -las node_modules
            - ls -las /root/node_modules
            - npm --global cache verify            