resources:
  {{ range $i, $pipe := until 10000 }}
  - name: git_resource_{{ $i }}
    type: GitRepo
    configuration:
      path: kunal-mazumdar/pipelines-local-test-repo
      gitProvider: kunal_gh
      branches:
        include: ^{{ gitBranch }}$
  {{ end }}

pipelines:
{{ range $i, $pipe := until 10 }}
  - name: loop_pipeline_{{ $i }}
    configuration:
      jfrogCliVersion: 2
    steps:
    {{ range $j, $step := until 10 }}
      - name: step_{{ $j }}
        type: Bash
        configuration:
          inputResources:
            - name: git_resource_1
        execution:
          onExecute:
            - echo "test1234513"
    {{ end }}
{{ end }}