resources:
  - name: jfrog_playground
    type: GitRepo
    configuration:
      gitProvider: kunal_gh
      path: kunal-mazumdar/node-js-sample
      branches:
        include: master

pipelines:
  - name: local_cache_test
    configuration:
      nodePool: local_cache
      runtime:
        type: image
        image:
          custom:
            name: releases-docker.jfrog.io/jfrog/pipelines-u20node
            tag: 18.18.2
            options: -v ~/node_modules:/root/node_modules

    steps:
      - name: test
        type: Bash
        configuration:
          inputResources:
            - name: jfrog_playground
              trigger: true
        execution:          
          onExecute:
            - ls -las /root/node_modules
            - cd ${res_jfrog_playground_resourcePath}            
            - pwd
            - ls -las
            - npm i --verbose
            - ls -las node_modules
            - ls -las /root/node_modules