resources:
  - name: git_resource
    type: GitRepo
    configuration:
      path: kunal-mazumdar/pipelines-local-test-repo
      gitProvider: kunal_gh
      branches:
        include: ^{{ .jfrog-pipelines.gitBranch }}$

{{ range $i, $e := until 1000 }}
pipelines:
  - name: loop_pipeline_{{ $i }}
    configuration:
      jfrogCliVersion: 2
    steps:
      - name: step
        type: Bash
        configuration:
          inputResources:
            - name: git_resource
        execution:
          onExecute:
            - echo "test1234513"
{{ end }}