valuesFilePath: ./values.yml

resources:
  - name: git_sonar_1
    type: CodeAnalysis
    configuration:
      tool: SonarCloud
      provider:
        integration: sonar_int
        urlKey: sonar_user_name
        tokenKey: sonar_token

pipelines:
  - name: code_analysis_pipe
    configuration:
      jfrogCliVersion: 2      
    steps:
      - name: my_first_step
        type: Bash
        configuration:
          outputResources:
            - name: git_sonar_1
        execution:
          onExecute:
            - printenv
            - write_output git_sonar_1 "urlKey=some_key"
