pipelines:
  - name: pde_pipeline
    configuration:
      jfrogCliVersion: 2
    steps:
      - name: my_first_step
        type: Bash
        execution:
          onExecute:
            - echo "test1234513"
