valuesFilePath: ./values.yml

{{ $res := "git_sonar" }}
resources:
  - name: {{ $res }}
    type: CodeAnalysis
    configuration:
      tool: SonarCloud
      provider:
        integration: sonar_int
        urlKey: sonar_user_name
        tokenKey: sonar_token

pipelines:
  - name: code_analysis_pipe
    configuration:
      jfrogCliVersion: 2      
    steps:
      - name: my_first_step
        type: Bash
        configuration:
          outputResources:
            - name: {{ $res }}
        execution:
          onExecute:
            - printenv
            - write_output {{ $res }} "codeDuplicationPercent=0"
            - write_output {{ $res }} "linesOfCode=1500"
            - write_output {{ $res }} "duplicateBlocks=8"
            - write_output {{ $res }} "coveragePercent=0.0"
            - write_output {{ $res }} "bugs=10"
            - write_output {{ $res }} "vulnerabilities=19"
            - write_output {{ $res }} "codeSmells=7"
            - write_output {{ $res }} "hotspots=3"
