template: true
valuesFilePath: ../values.yml

resources:
  - name: P_SYC_Pipelines_6196_001_git_repo
    type: GitRepo
    configuration:
      gitProvider: kunal_gh
      path: {{ .Values.GitHub.Org_test_Automation.path }}
      branches:
        include: master

pipelines:
  - name: test_pipeline1
    steps:
      - name: step1
        type: Bash
        execution:
          onExecute:
            - echo "P_SYC_Pipelines_6196_001"
