resources:
  - name: pr_repo_x
    type: GitRepo
    configuration:
      gitProvider: kunal_gh
      path: kunal-mazumdar/pipelines-local-test-repo
      buildOn:
        branchCreate: false
        commit: true
        pullRequestCreate: false

  - name: myAqlResource
    type: Aql
    configuration:
      sourceArtifactory: myArtifactoryIntegration
      query: items.find({"repo":"example-repo-local"},{"name":"tools/pipelines-template"})

  - name: myFileSpec
    type: FileSpec
    configuration:
      sourceArtifactory: s_artifactory
      flat: true
      target: "/tmp"
      aql: myAqlResource

pipelines:
  - name: pr_pipe_x
    steps:
      - name: pr_step
        type: Bash
        configuration:
          inputResources:
            - name: pr_repo_x
            - name: myFileSpec
        execution:
          onExecute:
            - echo ${res_pr_repo_x_isPullRequest}
