resources:
  - name: jfrog_playground
    type: GitRepo
    configuration:
      gitProvider: kunal_gh
      path: kunal-mazumdar/pipelines-local-test-repo
      branches:
        include: sanity

pipelines:
  - name: top_embed_pipeline
    steps:
      - name: compare_git
        type: Bash
        configuration:
          inputResources:
            - name: jfrog_playground
              trigger: true
        execution:
          onExecute:
            - add_run_variables var1="true"

      - name: scan_controller
        type: TriggerPipeline
        configuration:
          condition: 'var1 == "true"'
          pipelineName: scanner_embed_pipeline
          stepName: scan_it
          integrations:
            - name: jf_token
          environmentVariables:
            scan_target:
              default: 'hello-world 777'
              allowCustom: true
              values:
                - "vault"
                - "redis"
                - "postgresql"
                - "hello-world"
          inputSteps:
            - name: compare_git
              status:
                - success
        execution:
          onStart:
            - echo $var1
            - set_trigger_payload pipelineVariables "scan_target=${scan_target}"
            - set_trigger_payload stepVariables "notify=email" "uploadReport=true"
          onComplete:
            - echo "Final status is $nested_run_status"

  - name: scanner_embed_pipeline
    steps:
      - name: scan_it
        type: Bash
        configuration:
          integrations:
            - name: jf_token
        execution:
          onExecute:
            - echo "Image to scan is $scan_target. !!!"
            - echo "Triggered by parent step at $parent_step_url"